### ISSUE TITLE
investigate chart.js -- how to use it?

### ISSUE THREAD

**Issue by knees4bees** [rdtho2525/Refactor-Tractor#11]
- [x] Draft charts
- [ ] Insert data from server

https://www.chartjs.org/

David sez: "I think chart.js works well! It’s definitely the quickest option. If you really wanted a challenge, you could also consider D3."

Lucas from Mod 3 sez:
- there are YouTube videos available
- we can consult his GH repo if needed and/or ask him questions
- best way forward is to get it implemented and then build one chart to play around with
- can set up in two ways: 
  - (more difficult option) as a dependency
  - (easier but not as clean option) import via a scripts tag in html; charts will need to live in our main js file and in onload functions
  - if the easy way goes smoothly enough, we can always implement the dependency way later to make things cleaner

**Comment by rdtho2525** [comment]
Status update: Chart.js is imported and rendered; now determining how to display appropriate data.
